// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5PmkOqC7a8iwJmh3p6IzLeISRWgQPMbI',
    appId: '1:767810510644:web:e1e4aac9162a5d78250f61',
    messagingSenderId: '767810510644',
    projectId: 'drugenius-44d32',
    authDomain: 'drugenius-44d32.firebaseapp.com',
    storageBucket: 'drugenius-44d32.appspot.com',
    measurementId: 'G-1JNJF32FEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjwq_QjjSt0jgLGfzqPWHNwv-oE3uzFXQ',
    appId: '1:767810510644:android:f8d8cc159f8d5e57250f61',
    messagingSenderId: '767810510644',
    projectId: 'drugenius-44d32',
    storageBucket: 'drugenius-44d32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs9pJ45XFjB0VllrXUX8_EIiOM-GejQKU',
    appId: '1:767810510644:ios:949f1332f1ceae50250f61',
    messagingSenderId: '767810510644',
    projectId: 'drugenius-44d32',
    storageBucket: 'drugenius-44d32.appspot.com',
    iosBundleId: 'com.example.drugenius',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs9pJ45XFjB0VllrXUX8_EIiOM-GejQKU',
    appId: '1:767810510644:ios:a93ae5f9410bdfe6250f61',
    messagingSenderId: '767810510644',
    projectId: 'drugenius-44d32',
    storageBucket: 'drugenius-44d32.appspot.com',
    iosBundleId: 'com.example.drugenius.RunnerTests',
  );
}
